SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME FROM ANIMAL_INS AS A
    JOIN ANIMAL_OUTS AS B
        ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE LOCATE('intact', A.SEX_UPON_INTAKE) >= 1 AND
        LOCATE('intact', B.SEX_UPON_OUTCOME) = 0