SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
WHERE H.CAR_ID IN (SELECT HH.CAR_ID 
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HH
                  WHERE DATE_FORMAT(HH.START_DATE, '%Y-%m') BETWEEN "2022-08" AND "2022-10"
                  GROUP BY HH.CAR_ID
                  HAVING COUNT(*) >= 5)
    AND DATE_FORMAT(H.START_DATE, '%Y-%m') BETWEEN "2022-08" AND "2022-10"

GROUP BY MONTH, H.CAR_ID
HAVING COUNT(*) != 0 
ORDER BY MONTH ASC, CAR_ID DESC