SELECT p.product_id, p.product_name, sum(P.price*O.AMOUNT) as total_sales  
from FOOD_PRODUCT P
JOIN FOOD_ORDER O ON P.PRODUCT_ID=O.PRODUCT_ID
WHERE O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME
ORDER BY 3 DESC, 1;