-- 코드를 입력하세요
SELECT MEMBER_ID,MEMBER_NAME,GENDER,  	
 DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE 
where  MONTH(DATE_OF_BIRTH)=03 and GENDER='W' and  not TLNO is Null
Order by MEMBER_ID ASC;